### Light Colors:

set $black #000000
set $white #ffffff
set $grey_3 #333333
set $grey_6 #666666
set $grey_9 #999999
set $grey_c #cccccc

set $active_bg $white
set $active_text $black
set $alert_bg #99cc33
set $alert_text $white

# _border is for window title box border color
# _background is for the actual window border color
set $cf_border $active_bg
set $cf_background $cf_border
set $cf_text $active_text
set $cf_indicator $alert_bg

# _border is for window title box border color
# _background is for the actual window border color
set $cu_border $grey_3
set $cu_background $cu_border
set $cu_text $grey_6
set $cu_indicator $alert_bg

# _border is for window title box border color
# _background is for the actual window border color
set $cfi_border $grey_3
set $cfi_background $cfi_border
set $cfi_text $grey_c
set $cfi_indicator $alert_bg

# <class> border background text indicator child_border
client.focused $cf_border $cf_background $cf_text $cf_indicator
client.unfocused $cu_border $cu_background $cu_text $cu_indicator
# The most recently focused window within a container which is not focused.
client.focused_inactive $cfi_border $cfi_background $cfi_text $cfi_indicator

### bar colors

set $bar_background $black

set $fw_border $active_bg
set $fw_background $fw_border
set $fw_text $active_text

set $iw_border $grey_6
set $iw_background $black
set $iw_text $grey_9

set $uw_border $alert_bg
set $uw_background $uw_border
set $uw_text $alert_text

# Read `man 5 sway-bar` for more information about this section.
bar bar-0 {
    colors {
        background $bar_background
        statusline $white
        # <class> border background text
        focused_workspace $fw_border $fw_background $fw_text
        inactive_workspace $iw_border $iw_background $iw_text
        urgent_workspace $uw_border $uw_background $uw_text
    }
}

unbindsym $mod+d
bindsym $mod+d exec wlctl.sh dynamic-menu -S '$active_bg' -s '$active_text'
